Post http://localhost:3001/permisos
content-type: application/json



###
POST http://localhost:3001/asignarPermisos
content-type: application/json

{"usuario":{"email":"martin.resnicoff@enel.com"},
"permisos":["LOG"]}
###
GET http://localhost:3001/getdatos?zona=General%20Paz